name: ${CHATTER_ROLE:-talker}

services:
  chatter:
    build: .
    network_mode: service:husarnet
    depends_on: 
      husarnet: { condition: service_healthy } # husarnet service is healthy if all hosts listed in WAIT_HOSTNAMES are reachable
    volumes:
      - ./fastdds.xml:/var/tmp/fastdds.xml
      - ./cyclonedds.xml:/var/tmp/cyclonedds.xml
    environment:
      # - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # - FASTRTPS_DEFAULT_PROFILES_FILE=/var/tmp/fastdds.xml
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///var/tmp/cyclonedds.xml
      - ROS_STATIC_PEERS=talker-host;listener-host
      # - ROS_STATIC_PEERS=fc94:338e:5919:1541:9358:9b14:9070:dd07;fc94:a9fe:58ff:86d6:a671:d3e0:528d:bf3c
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
    command: ros2 run demo_nodes_cpp ${CHATTER_ROLE:-talker}

  husarnet:
    image: husarnet/husarnet:2.0.180
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=${CHATTER_ROLE:-talker}-host
      - JOINCODE
      # - HUSARNET_DEBUG=1
      - WAIT_HOSTNAMES=talker-host, listener-host